### ISSUE TITLE
[Bug]: Exception: Hote inconnu (authserver.mojang.com)

### ISSUE THREAD

**Issue by vortexModding** [MLDEG/Ragnamod_VII#105]
### Modpack version

1.7.3/7.1.4

### Description

les deux dernière version impossible a installer sa me donne toujours la même erreur :/ j'ai essayer sur 2 pc différent 

### Crashlogs

Forge not installed, installing now.
Running Forge installer.
JVM info: Oracle Corporation - 17.0.7 - 17.0.7+8-LTS-224
java.net.preferIPv4Stack=true
Current Time: 10/03/2024 17:14:24
Host: files.minecraftforge.net [51.79.83.165, 2607:5300:203:65a5:0:0:0:0]
Host: maven.minecraftforge.net [51.79.83.165, 2607:5300:203:65a5:0:0:0:0]
Host: libraries.minecraft.net [13.107.246.42, 13.107.213.42, 2620:1ec:bdf:0:0:0:0:42, 2620:1ec:46:0:0:0:0:42]
Host: launchermeta.mojang.com [13.107.246.42, 13.107.213.42, 2620:1ec:bdf:0:0:0:0:42, 2620:1ec:46:0:0:0:0:42]
Host: piston-meta.mojang.com [13.107.213.42, 13.107.246.42, 2620:1ec:46:0:0:0:0:42, 2620:1ec:bdf:0:0:0:0:42]
java.net.UnknownHostException: H¶te inconnu (authserver.mojang.com)
        at java.base/java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
        at java.base/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:933)
        at java.base/java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1543)
        at java.base/java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:852)
        at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1532)
        at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1384)
        at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1305)
        at net.minecraftforge.installer.DownloadUtils.getIps(DownloadUtils.java:290)
        at net.minecraftforge.installer.SimpleInstaller.main(SimpleInstaller.java:120)
Exception in thread "main"
java.lang.NullPointerException: Cannot invoke "java.util.List.stream()" because the return value of "net.minecraftforge.installer.DownloadUtils.getIps(String)" is null
        at net.minecraftforge.installer.SimpleInstaller.main(SimpleInstaller.java:120)
Error: could not open `libraries/net/minecraftforge/forge/1.18.2-40.2.17/win_args.txt'

### Steps to reproduce

juste lancer les serveur

### Expected behavior

lancer le serveur

**Comment by neomatamune** [comment]
Pour corriger le problème il faut retélécharger l'installeur forge (même version mais un fichier plus récent) un dns a été changé pour l'authentification et les anciens installeurs ne marchent plus

**Comment by MLDEG** [comment]
tout est dans ton titre...

authserver.mojang.com

**Comment by vortexModding** [comment]
> Pour corriger le problème il faut retélécharger l'installeur forge (même version mais un fichier plus récent) un dns a été changé pour l'authentification et les anciens installeurs ne marchent plus

merci beaucoup pour ta réponse   plus pertinente que MLDEG je pouvais pas deviner ça
