### ISSUE TITLE
[Bug]: Mauvais forge dans le pack de serveur

### ISSUE THREAD

**Issue by Zekirax** [MLDEG/Ragnamod_VII#119]
### Modpack version

7.1.5

### Description

Dans les pack de serveur il y'a un mauvais forge. Dans l'annonce sur le discord Forge il y'a une annonce [message_discord](https://discord.com/channels/1129059589325852724/1129077934330744882/1212091927038533662) qui annonce le faite que mojang a changé ces nom de domaine. Il suffit de retélécharger la même version.

### Crashlogs

Host: files.minecraftforge.net [104.21.58.163, 172.67.161.211]
Host: maven.minecraftforge.net [172.67.161.211, 104.21.58.163]
Host: libraries.minecraft.net [13.107.246.62, 13.107.213.62]
Host: launchermeta.mojang.com [13.107.246.45, 13.107.213.45]
Host: piston-meta.mojang.com [13.107.213.45, 13.107.246.45]
java.net.UnknownHostException: authserver.mojang.com: Name or service not known
        at java.base/java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method)
        at java.base/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:934)
        at java.base/java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1543)
        at java.base/java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:852)
        at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1533)
        at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1385)
        at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1306)
        at net.minecraftforge.installer.DownloadUtils.getIps(DownloadUtils.java:290)
        at net.minecraftforge.installer.SimpleInstaller.main(SimpleInstaller.java:120)
Exception in thread "main" 
java.lang.NullPointerException: Cannot invoke "java.util.List.stream()" because the return value of "net.minecraftforge.installer.DownloadUtils.getIps(String)" is null
        at net.minecraftforge.installer.SimpleInstaller.main(SimpleInstaller.java:120)

### Steps to reproduce

Lancer le startserver.sh

### Expected behavior

Le serveur devrait ce lancer en téléchargeant le serveur. 

### Anything else to note?

C'est le cas avec les anciens pack de serveur.

**Comment by MLDEG** [comment]
Fix :)
https://legacy.curseforge.com/minecraft/modpacks/ragnamod-vii/files/5250934
